Refactor modules in many-rs and add support for async.status in abci …
l-1-labs/many-framework pull request #57
Opened 2022-04-12 02:55 UTC by hansl

…frontend

This is the framework followup for https://github.com/l-1-labs/many-rs/pull/43

This will fail CI until the PR in many-rs is merged and I update the dependencies.

2022-04-12 18:15 UTC, fmorency requested changes
Not sure if this is expected/normal, but the `run.sh` script behavior is different between this version and `main`.

The output of the `tendermint-ledger` window progress **much slower** than before... I feel that everything is _slower_.

2022-04-12 18:34 UTC, hansl commented
Yes I needed to slow down block production to test the async attribute. That's the `toml_set` changes you see. This PR doesn't work without the `many-rs` PR anyway so I'll fix it when the other one is merged.

2022-04-14 13:36 UTC, fmorency commented
Let's aim to merge this today if possible, I need this to push my first `coset` draft.

2022-04-14 14:28 UTC, hansl commented on src/many-kvstore/src/module.rs
> +impl KvStoreCommandsModuleBackend for KvStoreModuleImpl {
Done.

2022-04-14 14:29 UTC, fmorency approved these changes

2022-04-14 14:36 UTC, merged